package controllers

import (
	"strconv"

	"bubblewhite-backend/models"
	"bubblewhite-backend/services"
	"bubblewhite-backend/utils"

	"github.com/gin-gonic/gin"
)

type CategoryController struct {
	Service *services.CategoryService
}

func NewCategoryController(s *services.CategoryService) *CategoryController {
	return &CategoryController{Service: s}
}

// GET /api/categories — public, only active categories
func (ctrl *CategoryController) List(c *gin.Context) {
	categories, err := ctrl.Service.ListPublic()
	if err != nil {
		utils.InternalError(c, "failed to fetch categories")
		return
	}
	utils.OK(c, categories)
}

// GET /api/admin/categories (requires category.view) — every category
// regardless of active status, so staff can find and re-enable a disabled
// one that wouldn't show up in the public listing above.
func (ctrl *CategoryController) ListAdmin(c *gin.Context) {
	categories, err := ctrl.Service.ListAdmin()
	if err != nil {
		utils.InternalError(c, "failed to fetch categories")
		return
	}
	utils.OK(c, categories)
}

// GET /api/categories/:id
func (ctrl *CategoryController) GetByID(c *gin.Context) {
	id, err := strconv.ParseUint(c.Param("id"), 10, 64)
	if err != nil {
		utils.BadRequest(c, "invalid category id")
		return
	}
	cat, err := ctrl.Service.GetByID(uint(id))
	if err != nil {
		utils.NotFound(c, "category not found")
		return
	}
	utils.OK(c, cat)
}

// categoryInput has no ID field — categories.id is an auto-increment
// primary key now, generated by the database, never supplied by the client.
type categoryInput struct {
	Name      string `json:"name" validate:"required"`
	Slug      string `json:"slug" validate:"required"`
	Image     string `json:"image"`
	SortOrder int    `json:"sortOrder"`
	IsActive  bool   `json:"isActive"`
}

// POST /api/admin/categories (requires category.create permission)
func (ctrl *CategoryController) Create(c *gin.Context) {
	var in categoryInput
	if err := c.ShouldBindJSON(&in); err != nil {
		utils.BadRequest(c, "invalid request body")
		return
	}
	if errs, _ := utils.ValidateStruct(in); errs != nil {
		utils.FailWithErrors(c, errs)
		return
	}

	// Slug is admin-chosen and unique, so a collision is a normal mistake —
	// check for it up front and return a friendly field-level error instead
	// of a raw "duplicate entry" database error.
	if _, err := ctrl.Service.GetBySlug(in.Slug); err == nil {
		utils.FailWithErrors(c, map[string]string{"slug": "Slug នេះមានរួចហើយ សូមប្រើ slug ផ្សេង"})
		return
	}

	cat := models.Category{Name: in.Name, Slug: in.Slug, Image: in.Image, SortOrder: in.SortOrder, IsActive: in.IsActive}
	if err := ctrl.Service.Create(&cat); err != nil {
		if isDuplicateKeyError(err) {
			utils.FailWithErrors(c, map[string]string{"slug": "Slug នេះមានរួចហើយ សូមប្រើ slug ផ្សេង"})
			return
		}
		utils.InternalError(c, "failed to create category")
		return
	}
	utils.Created(c, cat)
}

// PUT /api/admin/categories/:id (requires category.update permission)
func (ctrl *CategoryController) Update(c *gin.Context) {
	id, err := strconv.ParseUint(c.Param("id"), 10, 64)
	if err != nil {
		utils.BadRequest(c, "invalid category id")
		return
	}

	cat, err := ctrl.Service.GetByID(uint(id))
	if err != nil {
		utils.NotFound(c, "category not found")
		return
	}

	var in categoryInput
	if err := c.ShouldBindJSON(&in); err != nil {
		utils.BadRequest(c, "invalid request body")
		return
	}

	cat.Name = in.Name
	cat.Slug = in.Slug
	cat.SortOrder = in.SortOrder
	cat.IsActive = in.IsActive
	// Always assign — this is a full PUT, and the frontend always sends the
	// image field's complete current state (including "" when the admin
	// removed it). Skipping the assignment on an empty string silently
	// ignored image removals, leaving the old URL stuck in the database
	// even after the file itself was deleted from R2.
	cat.Image = in.Image

	if err := ctrl.Service.Update(cat); err != nil {
		utils.InternalError(c, "failed to update category")
		return
	}
	utils.OK(c, cat)
}

// DELETE /api/admin/categories/:id (requires category.delete permission)
func (ctrl *CategoryController) Delete(c *gin.Context) {
	id, err := strconv.ParseUint(c.Param("id"), 10, 64)
	if err != nil {
		utils.BadRequest(c, "invalid category id")
		return
	}
	if err := ctrl.Service.Delete(uint(id)); err != nil {
		utils.InternalError(c, "failed to delete category")
		return
	}
	utils.NoContent(c)
}
